# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Infinitos monos
tagline:          'Antonio Maria Sanchez Berrocal'
description:      'Code snippets, cookbooks, boiler plates and programming stuff'
url:              http://antoniomaria.github.io
baseurl:          /

author:
  name:           'Antonio Maria Sanchez Berrocal'
  url:            https://twitter.com/amsb

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/antoniomaria
