name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if
          # etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          # ~/conda_pkgs_dir set via miniconda action
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
      - name: Make conda environment
        uses: conda-incubator/setup-miniconda@v2    # https://github.com/conda-incubator/setup-miniconda
        with:
          python-version: 3.7
          environment-file: environment.yaml
          auto-update-conda: true
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0.0
        with:
          branch: master
          dir_docs: docs
          sphinxapiopts: '--separate -o . ../'
          sphinxapiexclude: '../*setup* ../*.ipynb'
          sphinxopts: ''