name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Make conda environment
        uses: conda-incubator/setup-miniconda@v2    # https://github.com/conda-incubator/setup-miniconda
        with:
          python-version: 3.7
          environment-file: devtools/conda-envs/docs_env.yaml
          auto-update-conda: true
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0.0
        with:
          branch: main
          dir_docs: docs
          sphinxapiopts: '--separate -o . ../'
          sphinxapiexclude: '../*setup* ../*.ipynb'
          sphinxopts: ''